### ISSUE TITLE
CDP frame not correctly decoded

### ISSUE THREAD

**Issue by liedekef** [vincentbernat/lldpd#137] opened 2015-09-22 13:54 UTC
I have a cisco switch connected on eth2 of a CentOS 6 box, and it seems to be ignoring cdpv2 packets (-c option added to lldpd):
```
2015-09-22T15:47:41 [ DBG/event] received something for eth2
2015-09-22T15:47:41 [ DBG/receive] receive a frame on eth2
2015-09-22T15:47:41 [ DBG/interfaces] receive PDU from ethernet device eth2
2015-09-22T15:47:41 [ DBG/receive] decode received frame on eth2
2015-09-22T15:47:41 [ DBG/decode] decode a received frame on eth2
2015-09-22T15:47:41 [ DBG/decode] guessed protocol is CDPv1 (from detector function)
2015-09-22T15:47:41 [ DBG/decode] using decode function for CDPv1 protocol
2015-09-22T15:47:41 [ DBG/cdp] decode CDP frame received on eth2
2015-09-22T15:47:41 [ DBG/alloc] cleanup management addresses for chassis (unknown)
2015-09-22T15:47:41 [ DBG/alloc] cleanup chassis (unknown)
2015-09-22T15:47:41 [ DBG/decode] function for CDPv1 protocol did not decode this frame
```
Although tcpdump receives the package just fine (and it works fine on eth0 for cdp). See this tcpdump output (obfuscated some parts):
```
# tcpdump -nn -vvv -i eth2 -s 1500 -c 10 'ether[20:2] == 0x2000'
tcpdump: WARNING: eth2: no IPv4 address assigned
tcpdump: listening on eth2, link-type EN10MB (Ethernet), capture size 1500 bytes
15:50:49.938602 CDPv2, ttl: 180s, checksum: 692 (unverified), length 446
        Device-ID (0x01), length: 33 bytes: 'xxxxxxxxxxxxxx'
        Version String (0x05), length: 292 bytes:
          Cisco Internetwork Operating System Software
          IOS (tm) s72033_rp Software (s72033_rp-ENTSERVICESK9_WAN-M), Version 12.2(18)SXF16, RELEASE SOFTWARE (fc2)
          Technical Support: http://www.cisco.com/techsupport
          Copyright (c) 1986-2009 by cisco Systems, Inc.
          Compiled Tue 03-Mar-09 23:19 by kellythw
        Platform (0x06), length: 16 bytes: 'cisco WS-C6509-E'
        Address (0x02), length: 13 bytes: IPv4 (1) xxxxxxxxx
        Port-ID (0x03), length: 19 bytes: 'xxxxxxxxx'
        Capability (0x04), length: 4 bytes: (0x00000009): Router, L2 Switch
        VTP Management Domain (0x09), length: 0 byte: ''
15:50:49.938713 CDPv1, ttl: 180s, checksum: 436 (unverified), length 405
        Device-ID (0x01), length: 33 bytes: 'xxxxxxxxxx'
        Version String (0x05), length: 292 bytes:
          Cisco Internetwork Operating System Software
          IOS (tm) s72033_rp Software (s72033_rp-ENTSERVICESK9_WAN-M), Version 12.2(18)SXF16, RELEASE SOFTWARE (fc2)
          Technical Support: http://www.cisco.com/techsupport
          Copyright (c) 1986-2009 by cisco Systems, Inc.
          Compiled Tue 03-Mar-09 23:19 by kellythw
        Platform (0x06), length: 16 bytes: 'cisco WS-C6509-E'
        Address (0x02), length: 13 bytes: IPv4 (1) xxxxxxxxx
        Port-ID (0x03), length: 19 bytes: 'xxxxxxxxx'
        Capability (0x04), length: 4 bytes: (0x00000009): Router, L2 Switch
```
Maybe it is related to the fact that both cdpv1 and v2 packets are being received?

**Comment by vincentbernat** [comment] 2015-09-23 08:26
As a quick workaround, you can force CDPv2 only with `-cccc`.

CDPv2 may be ignored because lldpd decided that the remote peer was speaking CDPv1. I don't remember that there is any code to prefer CDPv2 over CDPv1. Maybe there should be something like that.

You have another oddities which is the inability to decode the CDP frame. Decoding is independent of the version. You get an error message about not being able to decode but it should have been another message explaining the cause. Could you send me by email your CDPv1 and CDPv2 packets? My email is on top of any source file.

**Comment by vincentbernat** [comment] 2016-02-28 12:22
No news, closing. Feel free to reopen with more information.

**Closed by vincentbernat** 2016-02-28 12:22 UTC
