### ISSUE TITLE
lldp under ubuntu VM, not sending lldp packets.

### ISSUE THREAD

**Issue by AJNOURI** [vincentbernat/lldpd#131] opened 2015-08-13 13:37 UTC
I have issue make lldp send packets under ubuntu vm

lldp & cdp protocols enabled 

**lldpd -c -dd**
>2015-08-13T11:12:36 [INFO/main] protocol LLDP enabled
>2015-08-13T11:12:36 [INFO/main] protocol CDPv1 enabled
>2015-08-13T11:12:36 [INFO/main] protocol CDPv2 enabled
>2015-08-13T11:12:36 [INFO/main] protocol SONMP disabled
>2015-08-13T11:12:36 [INFO/main] protocol EDP disabled
>2015-08-13T11:12:36 [INFO/main] protocol FDP disabled
>2015-08-13T11:12:36 [INFO/event] libevent 2.0.21-stable initialized with epoll method
>2015-08-13T11:12:36 [INFO/lldpctl] cannot find configuration file/directory /etc/lldpd.conf
>2015-08-13T11:12:36 [INFO/lldpctl] cannot find configuration file/directory /etc/lldpd.d
>2015-08-13T11:12:36 [INFO/localchassis] change detected for port eth0, resetting its timer
>2015-08-13T11:12:36 [INFO/localchassis] change detected for port eth1, resetting its timer
>2015-08-13T11:12:36 [INFO/lldpctl] lldpd should resume operations
>
The host is connected to 3 Cisco routers through a host bridge interface
Only one out of 3 devices is detected in ubuntu

***lldpctl***
>LLDP neighbors:
> 
>Interface:    eth1, via: LLDP, RID: 2, Time: 0 day, 00:00:20
>  Chassis:     
>    ChassisID:    mac aa:bb:cc:00:01:00
>    SysName:      IOU1
>    SysDescr:     Cisco IOS Software, Linux Software (I86BI_LINUX-ADVENTERPRISEK9-M), Version >15.2(2.15)T, ENGINEERING WEEKLY BUILD, synced to V151_4_M3_5
>Copyright (c) 1986-2012 by Cisco Systems, Inc.
>Compiled Sun 29-Jan-12 02:33 by 
>    MgmtIP:       192.168.11.100
>    Capability:   Bridge, off
>    Capability:   Router, on
>  Port:        
>    PortID:       ifname Et0/0
>    PortDescr:    Ethernet0/0
> 
># 

Wireshark shows lldp traffic from one Cisco routers and nothing from ubuntu
[Wireshark capture](https://drive.google.com/file/d/0BzYXUSsUVFR_d0tSSWVXYm9oeTQ/view?usp=sharing)

**lldpcli**
>[lldpcli] $ show configuration 
>
>Global configuration:
>
>Configuration:
>  Transmit delay: 30
>  Transmit hold: 4
>  Receive mode: no
>  Pattern for management addresses: (none)
>  Interface pattern: (none)
>  Interface pattern for chassis ID: (none)
>  Override description with: (none)
>  Override platform with: (none)
>  Advertise version: yes
>  Update interface descriptions: no
>  Disable LLDP-MED inventory: yes
>  LLDP-MED fast start mechanism: yes
>  LLDP-MED fast start interval: 1
>  Source MAC for LLDP frames on bond slaves: fixed
>
>[lldpcli] $ 

Through, eth1 shows lldp being sent

Even when forcing updates, nothing shown from the linux host outside

**lldpd update**

All cisco 3 routers see each other:
>IOU1#show cdp neighbors 
>Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge
>                  S - Switch, H - Host, I - IGMP, r - Repeater, P - Phone, 
>                  D - Remote, C - CVTA, M - Two-port Mac Relay 
>
>Device ID        Local Intrfce     Holdtme    Capability  Platform  Port ID
>IOU3             Eth 0/0            172              R    Linux Uni Eth 0/0
>IOU2             Eth 0/0            148              R    Linux Uni Eth 0/0
>IOU1#

**Comment by vincentbernat** [comment] 2015-08-13 13:54
From what I understand, you are running 3 IOU instances and 1 Ubuntu VM inside some Linux hosts and they are connected together through a bridged interface? In this case, I would say that LLDP frames should not cross such a bridge (it used a link local destination MAC address and those frames should not be forwarded by a switch). So, you shouldn't be able to see any IOU instances from Ubuntu. Oddly, you seem to be able to see one.

What's the output of `brctl` on your Linux host?

Also, lldpd tries to be smart when there are several hosts/protocols on the same link. This is something that shouldn't happen as there should not be several hosts on a given link but this sometimes happen because some switches leak one protocol and some others don't. Check with `show neighbors hidden` if you can see all the Cisco as CDP neighbors (as far as I know, Linux bridges let CDP frames pass).

**Comment by AJNOURI** [comment] 2015-08-13 15:18
Hi Vincent, Thanks for the prompt reply.
That's correct, all Cisco instances as well as the linux (container on which lldp installed) are virtual inside a linux host (physical) and connected through a bridge interface.
Sorry, I should have been more precise, the lldp in question is running on a linux container.

From the physical linux hosting all VMs:
***brctl show***
>bridge name	bridge id..........................STP enabled...interfaces
>br1 .............. 18000.0e62410b1a1f......	no....................vet1pl25483
>......................................................................................veth1pl25483

Looks like I missed the fact that LLDP is a link layer discovery protocol, so indeed cannot be forwarded.

Ok, that explains the whole dysfunctioning.

Maybe I should have asked if lldp works with docker containers? But knowing that docker host communicate with the containers through docker0, which a bridge interface, answers my question.

I verified this, the same behavior occurs, the container can see Cisco IOU but Cisco doesn't see lldp form the container.

**Comment by vincentbernat** [comment] 2015-08-13 15:36
❦ 13 août 2015 08:18 -0700, AJ NOURI <notifications@github.com> :

> Hi Vincent, Thanks for the prompt reply.
> That's correct, all Cisco instances as well as the linux (container on
> which lldp installed) are virtual inside a linux host (physical) and
> connected through a bridge interface.
> Sorry, I should have been more precise, the lldp in question is
> running on a linux container.
>
> From the physical linux hosting all VMs:
> brctl show
>
>     bridge name bridge id..........................STP
>     enabled...interfaces
>     br1 .............. 18000.0e62410b1a1f......
>     no....................vet1pl25483
>     ......................................................................................veth1pl25483
>    
> Looks like I missed the fact that LLDP is a link layer discovery
> protocol, so indeed cannot be forwarded.
>
> Ok, that explains the whole dysfunctioning.

This doesn't explain the partial visibility that you get. Looking at the
source code in Linux, I see that there is a selective forwarding for
LLDP frames. By default, no forwarding should happen. What is the
content of /sys/class/net/br1/bridge/group_fwd_mask? What is your kernel
version?

> Maybe I should have asked if lldp works with docker containers? But
> knowing that docker host communicate with the containers through
> docker0, which a bridge interface, answers my question.

The solution would be to run lldpd on the host (in addition to running
it in containers). I have also a plan to support LLDP inside containers
with an instance running only on the host but Linux kernel is still
missing a way to enumerate network namespaces.
-- 
Use library functions.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by AJNOURI** [comment] 2015-08-13 15:50
$ cat /sys/class/net/br1/bridge/group_fwd_mask
>0x0

$ uname -a
>Linux gns3-iouvm 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 >x86_64 GNU/Linux

$ lsb_release -a
>Distributor ID:	Ubuntu
>Description:	Ubuntu 14.04.3 LTS
>Release:	14.04
>Codename:	trusty

**Comment by vincentbernat** [comment] 2015-08-13 15:58
❦ 13 août 2015 08:50 -0700, AJ NOURI <notifications@github.com> :

> $ cat /sys/class/net/br1/bridge/group_fwd_mask
>
>     0x0
>
> $ uname -a
>
>     Linux gns3-iouvm 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29
>     11:21:34 UTC 2015 x86_64 x86_64 >x86_64 GNU/Linux

The code handling forwarding is here:
 http://lxr.free-electrons.com/source/net/bridge/br_input.c?v=3.13#L178

And in your case, I don't see why LLDP traffic is forwarded.

However, assuming that it is in fact forwarded, I think that your Ubuntu
container is receiving 3 CDP frames but only one LLDP (maybe LLDP is
disabled on two of the IOU instances?) and in this case, only the LLDP
one is displayed (because the 3 CDP ones are assumed to come from a
leaky switch).

`show neighbors hidden` should show you the 3 IOU.
-- 
Make sure special cases are truly special.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by AJNOURI** [comment] 2015-08-13 17:15
As you suggested, I installed also lldp on the host:
The 3 containers lldp detect the physical host and cisco IOU through docker0, but not each other: 

***root@pc2:/# lldpctl***
>
>LLDP neighbors:
>
>***Interface:    eth0, via: LLDP, RID: 2, Time: 0 day, 00:01:07***
>  Chassis:     
>    ChassisID:    mac 00:1f:16:f4:29:8b
>    SysName:      Uhost
>    SysDescr:     Ubuntu 14.04.3 LTS Linux 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 >UTC 2015 x86_64
>    MgmtIP:       192.168.0.121
>    Capability:   Bridge, on
>    Capability:   Router, on
>    Capability:   Wlan, off
>  Port:        
>    PortID:       mac c2:56:19:c6:ef:fc
>    PortDescr:    veth1ce128f
>
>***Interface:    eth0, via: LLDP, RID: 4, Time: 0 day, 00:00:52***
>  Chassis:     
>    ChassisID:    mac aa:bb:cc:00:01:00
>    SysName:      IOU1
>    SysDescr:     Cisco IOS Software, Linux Software (I86BI_LINUX-ADVENTERPRISEK9-M), Version >15.2(2.15)T, ENGINEERING WEEKLY BUILD, synced to V151_4_M3_5
>Copyright (c) 1986-2012 by Cisco Systems, Inc.
>Compiled Sun 29-Jan-12 02:33 by 
>    MgmtIP:       172.17.0.100
>    Capability:   Bridge, off
>    Capability:   Router, on
>  Port:        
>   PortID:       ifname Et0/0
>   PortDescr:    Ethernet0/0
>
>root@pc2:/# 

And from Cisco IOU connected to the bridge docker0, all containers are visible through CDP but not lldp:

***IOU1#sh lldp neighbors***
>Capability codes:
>    (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
>    (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
>
>Device ID           Local Intf     Hold-time  Capability      Port ID
>
>Total entries displayed: 0

***IOU1#sh cdp neighbors***
>Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge
>                  S - Switch, H - Host, I - IGMP, r - Repeater, P - Phone, 
>                  D - Remote, C - CVTA, M - Two-port Mac Relay 
>
>Device ID        Local Intrfce     Holdtme    Capability  Platform  Port ID
>pc3              Eth 0/0            98              R H   Linux     eth0
>pc2              Eth 0/0            80              R H   Linux     eth0
>pc1              Eth 0/0            71              R H   Linux     eth0
>IOU1#

For now I will settle for working CDP from Cisco IOS detecting all containers.
Looking forward for your contributions on lldp and containers.
Thank you very much Vincent.

**Comment by AJNOURI** [comment] 2015-08-13 17:28
It is even better,  show neighbors hidden shows all other containers, docker host and IOU : )

***[lldpcli] $ show neighbors hidden***
>
>LLDP neighbors:
>
>Interface:    eth0, via: LLDP, RID: 3, Time: 0 day, 00:19:53
>  Chassis:     
>    ChassisID:    mac aa:bb:cc:00:01:00
>    SysName:      ***IOU1***
>    SysDescr:     Cisco IOS Software, Linux Software (I86BI_LINUX-ADVENTERPRISEK9-M), Version >15.2(2.15)T, ENGINEERING WEEKLY BUILD, synced to V151_4_M3_5
>Copyright (c) 1986-2012 by Cisco Systems, Inc.
>Compiled Sun 29-Jan-12 02:33 by 
>    MgmtIP:       172.17.0.100
>    Capability:   Bridge, off
>    Capability:   Router, on
>  Port:        
>    PortID:       ifname Et0/0
>    PortDescr:    Ethernet0/0
>
***Interface:    eth0, via: LLDP, RID: 4, Time: 0 day, 00:19:53***
>  Chassis:     
>    ChassisID:    mac 00:1f:16:f4:29:8b
>    SysName:      ***Uhost***
>    SysDescr:     Ubuntu 14.04.3 LTS Linux 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 >UTC 2015 x86_64
>    MgmtIP:       192.168.0.121
>    Capability:   Bridge, on
>    Capability:   Router, on
>    Capability:   Wlan, off
>  Port:        
>    PortID:       mac 4a:5d:4c:7a:e2:b3
>    PortDescr:    veth2b0660a
>
>***Interface:    eth0, via: CDPv2, RID: 5, Time: 0 day, 00:19:33***
>  Chassis:     
>    ChassisID:    local IOU1
>    SysName:      ***IOU1***
>    SysDescr:     Linux Unix running on
>Cisco IOS Software, Linux Software (I86BI_LINUX-ADVENTERPRISEK9-M), Version 15.2(2.15)T, >ENGINEERING WEEKLY BUILD, synced to V151_4_M3_5
>Copyright (c) 1986-2012 by Cisco Systems, Inc.
>Compiled Sun 29-Jan-12 02:33 by 
>    MgmtIP:       172.17.0.100
>    Capability:   Router, on
>  Port:        
>    PortID:       ifname Ethernet0/0
>    PortDescr:    Ethernet0/0
>
>***Interface:    eth0, via: CDPv2, RID: 7, Time: 0 day, 00:18:40***
>  Chassis:     
>    ChassisID:    local pc2
>    SysName:      ***pc2***
>    SysDescr:     Linux running on
>Ubuntu 14.04.1 LTS Linux 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 >x86_64
>    MgmtIP:       172.17.0.6
>    Capability:   Router, on
>  Port:        
>    PortID:       ifname eth0
>    PortDescr:    eth0
>
>***Interface:    eth0, via: CDPv1, RID: 13, Time: 0 day, 00:10:29***
>  Chassis:     
>    ChassisID:    local IOU1
>    SysName:      ***IOU1***
>    SysDescr:     Linux Unix running on
>Cisco IOS Software, Linux Software (I86BI_LINUX-ADVENTERPRISEK9-M), Version 15.2(2.15)T, >ENGINEERING WEEKLY BUILD, synced to V151_4_M3_5
>Copyright (c) 1986-2012 by Cisco Systems, Inc.
>Compiled Sun 29-Jan-12 02:33 by 
>    MgmtIP:       172.17.0.100
>    Capability:   Router, on
>  Port:        
>    PortID:       ifname Ethernet0/0
>    PortDescr:    Ethernet0/0
>
>***Interface:    eth0, via: CDPv1, RID: 14, Time: 0 day, 00:08:19***
>  Chassis:     
>    ChassisID:    local pc1
>    SysName:      ***pc1***
>    SysDescr:     Linux running on
>Ubuntu 14.04.1 LTS Linux 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 >x86_64
>    MgmtIP:       172.17.0.5
>    Capability:   Router, on
>  Port:        
>    PortID:       ifname eth0
>    PortDescr:    eth0
>
>[lldpcli] $

**Comment by vincentbernat** [comment] 2015-08-13 17:47
The problem is that your bridge is forwarding LLDP frames (and CDP frames). This is not expected (at least for LLDP frames, this is expected for CDP which are not link local frames) and lldpd tries to do smart things because of that. You can disable the smart stuff (see the `-H` parameter for `lldpd`). But that's not a very good workaround. The ideal solution would be to run lldpd on the host, let all contained stuff see only the host they are connected to (but not each other) and lldpd running on the host should see everyone.

I just tested on my side with two Docker instances running lldpd, they don't see each other, as expected. Once I start lldpd on the host, each instance see the host and the host see the two instances.

Maybe you are running an alternate bridge implementation like OpenvSwitch?

**Comment by AJNOURI** [comment] 2015-08-13 19:41
I either used the default docker0 bridge interface or bridge interfaces created by pipework (which are the same), but not ovs.

**Comment by vincentbernat** [comment] 2015-08-13 20:37
Well, in this case, I have no clue on why those packets are forwarded by the bridge.

Assuming that your first intent was to work like that, it is a happy coincidence. To avoid to have to use `show neighbors hidden`, you can modify how lldpd handle multiple neighbors with the `-H` parameter. You can ask it to not filter anything.

**Comment by AJNOURI** [comment] 2015-08-14 01:51
Right Vincent, that was for labbing purposes, all I needed is a visibility (cdp) between a route and the containers connected to the bridge.
Appreciate your great help Vincent.

**Comment by vincentbernat** [comment] 2015-08-14 05:14
OK, so I am closing the issue, since it is somewhat "resolved".

**Closed by vincentbernat** 2015-08-14 05:14 UTC
