### ISSUE TITLE
Sending new customized tlvs periodically

### ISSUE THREAD

**Issue by zmingshi** [vincentbernat/lldpd#196] opened 2016-08-22 02:45 UTC
Hi, all

Currently, I'm trying to handle such an issue: there is one procedure periodically generating a set of data (period=100ms), the data then need to be sent out by lldpd periodically (e.g. period=2s). That is, within a lldpd period (2s), about 2(s)/100(ms) data need to be encapsulated into a customized tlv, and be sent out by lldpd. In next period, the new data will need to be encapsulated and sent out by lldpd, and so on... This should be a real-time process.
My problem is how to make lldpd periodically send out the data within its period (2s). One idea is to call lldpd periodically, after finishing to customize the tlv and send it out, then kill the lldpd. Is it ok or any better way to deal with? Thank you very much!

Best Regards

**Comment by vincentbernat** [comment] 2016-08-22 03:56
You can issue the "resume" command. That should trigger sending LLDPU.

**Comment by zmingshi** [comment] 2016-08-25 08:01
Hi, @vincentbernat 

I'm trying to use python to do such job. Each log generated by the data procedure includes several types of data (string, int, float), I think the log needs to be converted into ASCII text/hex (I'm not sure) first, before it is encapsulated into the customized tlv, right? If so, how could I deal with such conversion, thank you!

Best Regards!

**Comment by zmingshi** [comment] 2016-08-25 08:18
More specifically, how could I convert the data into a comma-separated list of bytes? Thank you very much!

**Comment by vincentbernat** [comment] 2016-08-25 08:21
You need to provide a comma-separated list of bytes. So:

```python
",".join(["{:02X}".format(x) for x in bytes])
```

**Comment by zmingshi** [comment] 2016-08-25 09:36
Hi,
I tried the code, `a='example'` `print ",".join(["{:02X}".format(a) for a in bytes])`, but the error occurs `TypeError: 'type' object is not iterable`
Sorry for that I'm not familiar with bytes, my python version is v2.7.9, thank you!

**Comment by vincentbernat** [comment] 2016-08-25 11:19
```
a='example'
print ",".join(["{:02X}".format(ord(x)) for x in a])
```

**Comment by zmingshi** [comment] 2016-08-26 08:17
Hi,
Thanks for your great help!
But sorry, I still have a puzzle, we have defined the format of the customized tlv. For example, the timestamp in the tlv is defined as time_t (8 octets). In my opinion, the timestamp should be converted to a 8-octets bytes with comma separated.
e.g. `t=1472193673.948` (ms timestamp). First, I convert it into a long type `t=1472193673948`, In order to convert it into a 8-octets bytes, I tried:
`t=str(t)
print ",".join(["{:02X}".format(ord(x)) for x in a])`
The output is `31,34,37,32,31,39,33,36,37,33,39,34,38`
But, I think it maybe not correct, each byte seems consists of '3' and the number. I also tried:
`print '%x' %t`
The output is `156c594badc`
I think the formatted bytes `00,00,01,56,c5,94,ba,dc` would be correct and encapsulated into the customized tlv, right?
Thank you!

**Comment by vincentbernat** [comment] 2016-08-26 09:03
You use `t=str(t)` but then you use `for x in a`. This has little to do with lldpd. I can't provide you support for Python stuff.

**Comment by zmingshi** [comment] 2016-08-28 10:45
Sorry to bother you, I'm not mean to ask for your Python support. You can omit my previous question.
Another problem: how to start lldpd without sending any LLDPDU? I plan to issue `resume` as you suggested to trigger the sending. Thank you!

**Comment by vincentbernat** [comment] 2016-08-28 18:15
You can use this in the configuration file:

```
configure lldp status rx-only
```

Use `rx-and-tx` when you are ready to send.

**Comment by zmingshi** [comment] 2016-08-31 07:42
Hi, @vincentbernat 
In my case, the data is generated every 100ms, the lldpdu transmission period is 2s, it means that 20 customized tlvs need to be configured by command `lldpcli configure lldp custom-tlv [add | replace] oui **oui** subtype **subtype** [oui-info **content**]`, so the command will be issued 20 times [python: os.system(command)]. I have tried such test, it shows that such command calling consumes much time, and it causes the actual lldpdu transmission period to be nearly 10s, which is not I expect.

Is there a way to configure multiple customized tlvs by issuing the command just once? Or if you have any suggestions to deal with such problem? Thank you~

**Comment by vincentbernat** [comment] 2016-08-31 08:04
There is no easy way. You can use the C API to program the TLV (look at the source code of lldpcli), but that's far from trivial. It will be easier to just build the LLDPDU yourself and send them on the wire.

**Comment by Robinieu** [comment] 2016-09-15 15:51
ghfhgffh

**Comment by vincentbernat** [comment] 2016-09-16 17:38
Dunno why I didn't think of it before. Put the commands in a file and use `lldpcli -c thefile`.

**Comment by vincentbernat** [comment] 2016-09-28 05:19
Not a bug, closing.

**Closed by vincentbernat** 2016-09-28 05:19 UTC
